version: '3.8'
services:
  wordpress-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: usr-wordpress
      MYSQL_PASSWORD: pwd-wordpress
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - wordpress_network
  wordpress1:
    depends_on:
      - wordpress-db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress_network
    volumes:
      - ./w1:/var/www/html
  wordpress2:
    depends_on:
      - wordpress-db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress_network
    volumes:
      - ./w2:/var/www/html
  wordpress3:
    depends_on:
      - wordpress-db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress_network
    volumes:
      - ./w1:/var/www/html
  nginx:
    image: nginx:latest

    restart: always
    ports:
      - 80:80
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./w1:/usr/share/nginx/html/wordpress1
      - ./w2:/usr/share/nginx/html/wordpress2
      - ./w3:/usr/share/nginx/html/wordpress3
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
